# Generated by Django 5.2.2 on 2026-03-06 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cc_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestorRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("company_or_representative", models.CharField(max_length=180)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
