# Generated by Django 5.2.2 on 2026-03-06 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cc_app", "0002_investorrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="investorrequest",
            name="access_token",
            field=models.CharField(blank=True, default="", max_length=6),
        ),
        migrations.AddField(
            model_name="investorrequest",
            name="token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
