# Generated by Django 5.2.2 on 2026-03-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cc_app", "0003_investorrequest_token_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="investorrequest",
            name="access_token",
        ),
        migrations.RemoveField(
            model_name="investorrequest",
            name="token_expires_at",
        ),
        migrations.AddField(
            model_name="investorrequest",
            name="password_hash",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
